package CmmdcApp;


/**
* CmmdcApp/Cmmdc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cmmdc.idl
* Sunday, November 25, 2018 7:51:26 PM EET
*/

public interface Cmmdc extends CmmdcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Cmmdc
