package CmmdcApp;


/**
* CmmdcApp/_CmmdcStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cmmdc.idl
* Monday, November 9, 2015 9:02:15 AM EET
*/

public class _CmmdcStub extends org.omg.CORBA.portable.ObjectImpl implements CmmdcApp.Cmmdc
{

  public long cmmdc (long a, long b)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("cmmdc", true);
                $out.write_longlong (a);
                $out.write_longlong (b);
                $in = _invoke ($out);
                long $result = $in.read_longlong ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return cmmdc (a, b        );
            } finally {
                _releaseReply ($in);
            }
  } // cmmdc

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CmmdcApp/Cmmdc:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CmmdcStub
