package CmmdcApp;


/**
* CmmdcApp/CmmdcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cmmdc.idl
* Monday, November 9, 2015 9:02:15 AM EET
*/

public interface CmmdcOperations 
{
  long cmmdc (long a, long b);
} // interface CmmdcOperations
