package CmmdcApp;


/**
* CmmdcApp/Cmmdc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cmmdc.idl
* Monday, November 9, 2015 9:02:15 AM EET
*/

public interface Cmmdc extends CmmdcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Cmmdc
