import java.net.Socket;
import java.io.DataInputStream;
import java.io.DataOutputStream;

public class VisualCmmdcClient extends javax.swing.JFrame {
    
    /** Creates new form VisualCmmdcClient */
    public VisualCmmdcClient() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        getContentPane().setLayout(new java.awt.GridLayout(5, 2));

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setText("Primul numar:");
        getContentPane().add(jLabel1);

        jTextField1.setText("1");
        getContentPane().add(jTextField1);

        jLabel2.setText("Al doilea numar:");
        getContentPane().add(jLabel2);

        jTextField2.setText("1");
        getContentPane().add(jTextField2);

        jButton1.setText("Calculeaza:");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        getContentPane().add(jButton1);

        jTextField3.setText("1");
        getContentPane().add(jTextField3);

        jLabel3.setText("Server Name:");
        getContentPane().add(jLabel3);

        jTextField4.setText("localhost");
        getContentPane().add(jTextField4);

        jLabel4.setText("Port:");
        getContentPane().add(jLabel4);

        jTextField5.setText("7999");
        getContentPane().add(jTextField5);

        pack();
    }//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // Add your handling code here:
        long m=(new Long(jTextField1.getText())).longValue();
        long n=(new Long(jTextField2.getText())).longValue();
        String host=jTextField4.getText();
        int port=(new Integer(jTextField5.getText())).intValue();
        try(Socket cmmdcSocket = new Socket(host, port);
            DataOutputStream out=new DataOutputStream(cmmdcSocket.getOutputStream());
            DataInputStream in=new DataInputStream(cmmdcSocket.getInputStream())){
          out.writeLong(m);
          out.writeLong(n);
          long r=in.readLong();
          jTextField3.setText(new Long(r).toString());
        } 
        catch (Exception e) {
            System.err.println("Connection Error : "+e.getMessage());
            System.exit(1);
        } 
    }//GEN-LAST:event_jButton1MouseClicked
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new VisualCmmdcClient().setVisible(true);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
    
}
